server:
  port: ${PORT:0}
spring:
  application:
    name: servicio-productos
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${sprig.application.name}:${spring.application.instance_id:${random.value}}