
spring:
  application:
    name: servicio-zuul-server
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    productos:
      service-id: servicio-productos
      path: /api/productos/**
    items:
      service-id: servicio-item
      path: /api/item/**
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 10000